### ISSUE TITLE
launch.py: error: argument --cors-allow-origins: expected one argument

### ISSUE THREAD

**Issue by wilzamguerrero** [daswer123/painthua-flask#1]
Hi man i use stable difussion in local for run painthua but i have this error

**Comment by wilzamguerrero** [comment]
5000/tcp:            13762
/content/stable-diffusion-webui
/content/painthua-flask/templates
 INPAINT/OUTPAINT Module
Optional module for import/outpaint that is linked to webui
Before you start use it, visit webui link
If you want change model, first, change it in webui, it also change for this module

 WEBUI
Wait for the model to load and follow this link


/content/stable-diffusion-webui
Python 3.9.1 (default, Dec 11 2020, 14:32:07) 
[GCC 7.3.0]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Launching Web UI with arguments: --deepdanbooru --xformers --api --cors-allow-origins
usage: launch.py
       [-h]
       [--config CONFIG]
       [--ckpt CKPT]
       [--ckpt-dir CKPT_DIR]
       [--gfpgan-dir GFPGAN_DIR]
       [--gfpgan-model GFPGAN_MODEL]
       [--no-half]
       [--no-half-vae]
       [--no-progressbar-hiding]
       [--max-batch-count MAX_BATCH_COUNT]
       [--embeddings-dir EMBEDDINGS_DIR]
       [--hypernetwork-dir HYPERNETWORK_DIR]
       [--localizations-dir LOCALIZATIONS_DIR]
       [--allow-code]
       [--medvram]
       [--lowvram]
       [--lowram]
       [--always-batch-cond-uncond]
       [--unload-gfpgan]
       [--precision {full,autocast}]
       [--share]
       [--ngrok NGROK]
       [--ngrok-region NGROK_REGION]
       [--enable-insecure-extension-access]
       [--codeformer-models-path CODEFORMER_MODELS_PATH]
       [--gfpgan-models-path GFPGAN_MODELS_PATH]
       [--esrgan-models-path ESRGAN_MODELS_PATH]
       [--bsrgan-models-path BSRGAN_MODELS_PATH]
       [--realesrgan-models-path REALESRGAN_MODELS_PATH]
       [--scunet-models-path SCUNET_MODELS_PATH]
       [--swinir-models-path SWINIR_MODELS_PATH]
       [--ldsr-models-path LDSR_MODELS_PATH]
       [--clip-models-path CLIP_MODELS_PATH]
       [--xformers]
       [--force-enable-xformers]
       [--deepdanbooru]
       [--opt-split-attention]
       [--opt-split-attention-invokeai]
       [--opt-split-attention-v1]
       [--disable-opt-split-attention]
       [--use-cpu {all,sd,interrogate,gfpgan,swinir,esrgan,scunet,codeformer} [{all,sd,interrogate,gfpgan,swinir,esrgan,scunet,codeformer} ...]]
       [--listen]
       [--port PORT]
       [--show-negative-prompt]
       [--ui-config-file UI_CONFIG_FILE]
       [--hide-ui-dir-config]
       [--freeze-settings]
       [--ui-settings-file UI_SETTINGS_FILE]
       [--gradio-debug]
       [--gradio-auth GRADIO_AUTH]
       [--gradio-img2img-tool {color-sketch,editor}]
       [--opt-channelslast]
       [--styles-file STYLES_FILE]
       [--autolaunch]
       [--theme THEME]
       [--use-textbox-seed]
       [--disable-console-progressbars]
       [--enable-console-prompts]
       [--vae-path VAE_PATH]
       [--disable-safe-unpickle]
       [--api]
       [--nowebui]
       [--ui-debug-mode]
       [--device-id DEVICE_ID]
       [--administrator]
       [--cors-allow-origins CORS_ALLOW_ORIGINS]
       [--tls-keyfile TLS_KEYFILE]
       [--tls-certfile TLS_CERTFILE]
       [--server-name SERVER_NAME]
launch.py: error: argument --cors-allow-origins: expected one argument

**Comment by daswer123** [comment]
Hi, now the localtunnel died which is why the links do not appear and that is why this error occurs.

I'm working on a solution right now

**Comment by daswer123** [comment]
The creators fixed the issue with localtunnel and now colab working

**Comment by wilzamguerrero** [comment]
thanks
